<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Asp.Versioning.Http" Version="10.0.1" />
        <PackageVersion Include="Asp.Versioning.OpenApi" Version="10.0.1" />
        <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.0.4" />
        <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="1.8.1" />
        <PackageVersion Include="Nerdbank.GitVersioning" Version="3.9.50" />
        <PackageVersion Include="PANiXiDA.Core.ResultPattern" Version="1.0.4" />
        <PackageVersion Include="Scalar.AspNetCore" Version="2.16.17" />
        <PackageVersion Include="Scalar.AspNetCore.Microsoft" Version="2.16.17" />
        <PackageVersion Include="xunit.v3" Version="3.2.2" />
        <PackageVersion Include="Shouldly" Version="4.3.0" />
    </ItemGroup>
</Project>
