<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <SonarQubeTestProject>true</SonarQubeTestProject>
        <PublishAot>true</PublishAot>
        <EnableRequestDelegateGenerator>true</EnableRequestDelegateGenerator>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/PANiXiDA.Core.Presentation.Http/PANiXiDA.Core.Presentation.Http.csproj" />
        <ProjectReference Include="../../src/PANiXiDA.Core.Presentation.Http.Generators/PANiXiDA.Core.Presentation.Http.Generators.csproj"
                          OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>
</Project>
