<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TestingPlatformCommandLineArguments>$(TestingPlatformCommandLineArguments) --coverage-settings "$(MSBuildProjectDirectory)/CodeCoverage.config.xml"</TestingPlatformCommandLineArguments>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
        <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\PANiXiDA.Core.Presentation.Http\PANiXiDA.Core.Presentation.Http.csproj" />
        <ProjectReference Include="../../src/PANiXiDA.Core.Presentation.Http.Generators/PANiXiDA.Core.Presentation.Http.Generators.csproj"
                          OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
        <Using Include="Shouldly" />
    </ItemGroup>
</Project>
