<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>true</IsPackable>

        <AssemblyName>PANiXiDA.Core.Presentation.Http</AssemblyName>

        <PackageId>PANiXiDA.Core.Presentation.Http</PackageId>
        <Description>Reusable HTTP presentation layer abstractions, endpoint conventions, and ASP.NET Core integration utilities for PANiXiDA applications.</Description>
        <PackageTags>PANiXiDA;Core;Presentation;Http;AspNetCore;WebApi;Endpoints;MinimalApi;ApiVersioning;Scalar;OpenApi;ProblemDetails</PackageTags>

        <RepositoryUrl>https://github.com/panixida-dotnet-core/presentation-http</RepositoryUrl>
        <PackageProjectUrl>https://github.com/panixida-dotnet-core/presentation-http</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http" />
        <PackageReference Include="Asp.Versioning.OpenApi" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Nerdbank.GitVersioning">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="PANiXiDA.Core.ResultPattern" />
        <PackageReference Include="Scalar.AspNetCore" />
        <PackageReference Include="Scalar.AspNetCore.Microsoft" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="PANiXiDA.Core.Presentation.Http.UnitTests" />
    </ItemGroup>
</Project>
